services:
  app:
    container_name: demo.app
    build:
      context: .
      dockerfile: app.dockerfile
    restart: always
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    container_name: demo.redis
    hostname: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  celery:
    container_name: demo.celery
    build:
      context: .
      dockerfile: celery_worker.dockerfile
    restart: always
    depends_on:
      - redis

  flower:
    container_name: demo.flower
    build:
      context: .
      dockerfile: flower.dockerfile
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - celery
