services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    restart: always
    ports:
      - 8000:8000

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: celery_worker.dockerfile
    restart: always
    depends_on:
      - redis

  flower:
    image: mher/flower
    command: celery -A tasks flower --basic-auth=test:test
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - celery
